### PR TITLE
make DynamicArray.opIndex return a ref T

### PR DESCRIPTION
**Pull request by burner**
so I can take the address of the underlaying memory

### CODE REVIEW

**Comment by Hackerpilot** [comment]
This means that we won't be able to reallocate or move memory internally because the pointers will be invalidated.

**Comment by burner** [comment]
that is true if you keep the pointer alive.

basically: if you want to do very bad stuff, you can. on your own risk

**Comment by burner** [comment]
I really could use access to the array, what about: @property T[] ptr();

**Comment by Hackerpilot** [comment]
I'll accept a pull request that adds a ".ptr" property. Just be sure that the documentation says that the pointer may be invalidated if items are added to the array.

**Comment by burner** [comment]
will do

**Comment by burner** [comment]
https://github.com/economicmodeling/containers/pull/12

**Pull request closed without merging**
