### PR TITLE
HashMap improvements

### PR DESCRIPTION
**Pull request by CyberShadow**
This PR adds some functionality I found missing compared to my own implementation (which needed some custom compiler patches, hence my attempt to migrate).

Please see the individual commits' commit messages for details and rationale.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Well..?

1. It imposes an unnecessary restriction onto the hashing function (e.g. 64-bit hash on a 32-bit architecture)
2. When the hash is stored in the object, it allows using a 32-bit hash on a 64-bit architecture to save memory

**Comment by Hackerpilot** [comment]
I'm not sure that point 1 is correct. Point 2 makes sense though.

**Comment by CyberShadow** [comment]
> I'm not sure that point 1 is correct

Sorry, how so? Granted I did make this PR some time ago...

**Comment by Hackerpilot** [comment]
Unless I'm misunderstanding something, `size_t` is 32-bits on 32-bit architectures so the problem is actually that I'm forcing the hash to be smaller on 32-bits than 64.

**Comment by CyberShadow** [comment]
No, that function is only for calculating the bucket index. If the hash is stored, it is compared against previous invocations of the user's hash function.

**Comment by CyberShadow** [comment]
@Hackerpilot Ping

**Comment by CyberShadow** [comment]
Applied two of the HashMap improvements to HashSet as well.

**Pull request merged**
